### ISSUE TITLE
It takes too long for pages to appear

### ISSUE THREAD

**Issue by speirling** [speirling/songbook#10]
The wait from loading the site - or submitting a change - until the page is rendered, is far too long.
Probably the json generation - or interpreting the whole database as json - takes too long.

**Comment by epeelo** [comment]
This was fixed to some extent by the re-introduction of online rendering. It's much quicker except for some playlists. (pr-15)

**Comment by speirling** [comment]
This issue isn't relevant to the new CakePHP3 songbook - backend rendering. Some slowness has been seen that could result from faulty router - also fixed - so I'll close this and open another issue if required.
