### ISSUE TITLE
Re-engineer system to use databases to leverage CakePHP

### ISSUE THREAD

**Issue by epeelo** [speirling/songbook#32]
Keys should be associated with both songs and singers... and these 'song instances' should be reusable. Tags are required, and starring... 

...so maybe I should bite the bullet and put all elements into the mysql database, including playlists and sets.

This would allow sets to be re-used easily, for songs to be aware what key they should be in for different performers, what performers are available etc.

Set up tables, and 'bake' an UI with cakePHP.

**Comment by speirling** [comment]
I think 'song instances' are too complicated to implement automatically in CakePHP3. Playlists should be tables though, the principle of using database tables instead of XML is right I think.

**Comment by speirling** [comment]
##Songs
Already working
##Sets
Sets are lists of songs, in order. Each entry in a set includes performer and key - in the sets table.
Should a set contain other sets, or should there be groups of sets? Allowing sets to include sets would make it fully recursive - is that a valid model?
sets as one table, and groups (playlists) as another might be simpler to autogenerate in Cake.
Also, sets dont have performer/key. They might have an act, but that more properly belongs to the group
##Playlists
Lists of Sets inorder, with act, and optionally venue&date ... more likely a playlist will be reused at many venues and dates, but most likely only with the one act.
##Instances - song was well received
"Star" a song - record time and date of star (act/venue?)
##Instance-song was used
Compile playlists of songs actually played. Maybe combine with starred - Instance = time&date, well recieved badly received or neutral?
##Tags
Tag a  song

**Comment by speirling** [comment]
#### Songs
Already working
#### Sets
id, title
#### SetSongs
set_id, song_id, order (previous/next?),  performer_id, key
#### Playlists
id, title, act_id
#### PlaylistSets
playlist_id, set_id, order (previous/next?)
#### SongPerformanceInstance
timestamp, song_id, set_id, flavour (well received, badly received, neutral)
#### Tags
id, title
#### SongTags
song_id, tag_id

**Comment by speirling** [comment]
To recreate current (xml based) functionality, only the sets and playlists are required. Move the other tables out into separate issues.

**Comment by speirling** [comment]
SongPerformanceInstance: issue #40

**Comment by speirling** [comment]
Tags: issue #41

**Comment by speirling** [comment]
Performers table is required to identify both singers and acts.
It already exists in the database, as does Playlists, but there's also an acts table and acts_playlists pivot table that I think is too complex. 
Delete Acts and pivots, add performer_id column to playlists

**Comment by speirling** [comment]
DROP TABLE `acts` ,
`act_playlists` ,
`sets` ,
`set_song_instances` ,
`song_instances` ,
`song_tags` ,
`tags` ;

**Comment by speirling** [comment]
Delete from filesystem :
 * \\fps\www\songbook\src\Controller\SongInstancesController.php
 * \\fps\www\songbook\src\Controller\SongTagsController.php
 * \\fps\www\songbook\src\Controller\TagsController.php
 * \\fps\www\songbook\src\Controller\SetSongsController.php
 * \\fps\www\songbook\src\Controller\SetsController.php

**Comment by speirling** [comment]
Delete from Filesystem: 
* \\FPS\www\songbook\src\Model\Entity\SongInstance.php
* \\FPS\www\songbook\src\Model\Entity\SongTag.php
* \\FPS\www\songbook\src\Model\Entity\Tag.php
* \\FPS\www\songbook\src\Model\Entity\SetSong.php
* \\FPS\www\songbook\src\Model\Entity\Set.php

**Comment by speirling** [comment]
Delete from Filesystem:
* \\FPS\www\songbook\src\Model\Table\SongInstancesTable.php
* \\FPS\www\songbook\src\Model\Table\SongTagsTable.php
* \\FPS\www\songbook\src\Model\Table\TagsTable.php
* \\FPS\www\songbook\src\Model\Table\SetSongsTable.php
* \\FPS\www\songbook\src\Model\Table\SetsTable.php

**Comment by speirling** [comment]
Songbook not working - CakePHP error with

    SongInstances
    SongTags

**Comment by speirling** [comment]
Edit:
SongsController.php
 public function view($id = null)
    {
        $song = $this->Songs->get($id, [
            'contain' => ['SongInstances', 'SongTags']
        ]);

change to 
 public function view($id = null)
    {
        $song = $this->Songs->get($id);

**Comment by speirling** [comment]
Edit:
PerformersController.php
    public function view($id = null)
    {
        $performer = $this->Performers->get($id, [
            'contain' => ['SongInstances']
        ]);
change to
   public function view($id = null)
    {
        $performer = $this->Performers->get($id);

**Comment by speirling** [comment]
CREATE TABLE `music_admin`.`sets` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`title` VARCHAR( 255 ) NOT NULL ,
`performer_id` INT NOT NULL ,
`Comment` TEXT NOT NULL
) ENGINE = InnoDB COMMENT = 'Title metadata for lists of songs';

**Comment by speirling** [comment]
CREATE TABLE `music_admin`.`set_songs` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`set_id` INT NOT NULL ,
`song_id` INT NOT NULL ,
`order` INT NOT NULL ,
`performer_id` INT NOT NULL ,
`key` VARCHAR( 25 ) NOT NULL ,
`capo` TINYINT NOT NULL
) ENGINE = InnoDB;

**Comment by speirling** [comment]
ALTER TABLE `playlists` ADD `act_id` INT NOT NULL

**Comment by speirling** [comment]
That last column was an error! It's performer_id, not acti_id :-(
so
 ALTER TABLE `playlists` CHANGE `act_id` `performer_id` INT( 11 ) NOT NULL

**Comment by speirling** [comment]
Closed in Pull request #43
